"""empty message

Revision ID: 025095c24a42
Revises: 1944837bee5e
Create Date: 2023-03-15 19:01:16.416702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025095c24a42'
down_revision = '1944837bee5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites_chars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorites_char')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites_char',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name='favorites_char_character_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorites_char_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorites_char_pkey')
    )
    op.drop_table('favorites_chars')
    # ### end Alembic commands ###
